name: ◎ Docker Push
on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Publish to Dockerhub Registry
      uses: dawidd6/action-docker-publish-changed@v3
      with:
        name: projectdiscovery/nuclei
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
        platforms: linux/amd64,linux/arm64,linux/arm
        tag: latest